# Generated by Django 2.2.5 on 2019-10-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191010_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'домашняя страница', 'verbose_name_plural': 'домашние страницы'},
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='carousel_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='изображение'),
        ),
    ]
