# Generated by Django 2.2.5 on 2019-10-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191014_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagephone',
            name='landline_phone',
        ),
        migrations.RemoveField(
            model_name='homepagephone',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='homepagephone',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='номер телефона'),
        ),
    ]
