# Generated by Django 2.2.5 on 2019-10-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191014_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecarousel',
            old_name='slide_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='homepagecarousel',
            old_name='slide_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='homepagegallery',
            old_name='gallery_image',
            new_name='image',
        ),
    ]
