# Generated by Django 2.2.5 on 2019-10-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191015_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagerelatedlink',
            name='url',
            field=models.URLField(blank=True, help_text='Адрес', null=True),
        ),
    ]
