# Generated by Django 2.2.6 on 2019-10-26 16:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0011_auto_20191016_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(max_length=80, verbose_name='подпись')),
                ('full_description', wagtail.core.fields.RichTextField(blank=True, max_length=511, verbose_name='подробное описание')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='изображение')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('short_description', wagtail.core.fields.RichTextField(blank=True, max_length=254, verbose_name='краткое описание')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='изображение')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandlinePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='стационарный телефон')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='мобильный телефон')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(max_length=80, verbose_name='подпись')),
                ('url', models.URLField(blank=True, help_text='Адрес', null=True, unique=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepagegallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagegallery',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagephone',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'домашняя страница'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address',
            field=models.CharField(max_length=254, null=True, verbose_name='адрес агентства'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email',
            field=models.EmailField(max_length=80, null=True, verbose_name='электронная почта'),
        ),
        migrations.DeleteModel(
            name='HomePageCarousel',
        ),
        migrations.DeleteModel(
            name='HomePageGallery',
        ),
        migrations.DeleteModel(
            name='HomePagePhone',
        ),
        migrations.DeleteModel(
            name='HomePageRelatedLink',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_phone', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='landlinephone',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='landline_phone', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='gallerycard',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_card', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slide', to='home.HomePage'),
        ),
    ]
