# Generated by Django 2.2.6 on 2019-10-26 17:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191026_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='gallerycard',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='landlinephone',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='landline_phones', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_phones', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.HomePage'),
        ),
    ]
