# Generated by Django 2.2.5 on 2019-10-09 20:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetailpage',
            name='additional',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='countrydetailpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='описание'),
        ),
    ]
