# Generated by Django 2.2.5 on 2019-10-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20191010_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydetailpage',
            options={'verbose_name': 'Детальная информация о стране'},
        ),
    ]
