# Generated by Django 2.2.5 on 2019-10-14 11:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('countries', '0003_auto_20191010_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetailsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('country_name', models.CharField(max_length=80, verbose_name='название страны')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='описание')),
                ('additional', wagtail.core.fields.RichTextField(blank=True, verbose_name='дополнительная информация')),
                ('country_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Детальная информация о стране',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='CountryDetailPage',
        ),
    ]
