# Generated by Django 2.2.5 on 2019-10-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_countriespage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydetailspage',
            old_name='country_image',
            new_name='image',
        ),
    ]
