# Generated by Django 2.2.5 on 2019-10-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20191015_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydetailspage',
            name='country_name',
        ),
    ]
