# Generated by Django 2.2.6 on 2019-10-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_remove_countrydetailspage_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countriespage',
            options={'verbose_name': 'Выбор стран'},
        ),
        migrations.AddField(
            model_name='countriespage',
            name='details_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='countries.CountryDetailsPage', verbose_name='информация по стране'),
        ),
    ]
