# Generated by Django 2.2.6 on 2019-10-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_auto_20191024_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countriespage',
            name='details_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='countries.CountryDetailsPage', verbose_name='информация по стране'),
        ),
    ]
