# Generated by Django 2.2.6 on 2019-10-24 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('countries', '0009_auto_20191024_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Список стран',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='countrydetailspage',
            name='country_name',
            field=models.CharField(default=1, max_length=80, unique=True, verbose_name='название страны'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CountriesPage',
        ),
    ]
