# Generated by Django 2.2.5 on 2019-10-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name="what's App"),
        ),
    ]
