# Generated by Django 2.2.5 on 2019-10-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_auto_20191016_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'соцсети'},
        ),
    ]
